name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # Fails building tsdl
          # - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
          dune-cache: true

      - name: Update apt packages (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only --with-test
          # For matrix's terminal emulator demo
          opam install tsdl tsdl-ttf

      - name: Build and test matrix
        run: |
          opam exec -- dune build matrix
          opam exec -- dune build @matrix/runtest

      - name: Build and test toffee
        run: |
          opam exec -- dune build toffee
          opam exec -- dune build @toffee/runtest

      - name: Build and test mosaic
        run: |
          opam exec -- dune build mosaic
          opam exec -- dune build @mosaic/runtest
